dat:
  ==: com.crazicrafter1.lootcrates.Data
  debug: false
  update: true
  speed: 4
  unSelectedItem:
    ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: CHEST
    meta:
      ==: ItemMeta
      meta-type: TILE_ENTITY
      display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"???"}],"text":""}'
      lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Choose
        4 mystery chests, and"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"your
        loot will be revealed!"}],"text":""}'
      blockMaterial: CHEST
  selectedItem:
    ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: WHITE_STAINED_GLASS_PANE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"???"}],"text":""}'
      lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"You
        have selected this mystery chest"}],"text":""}'
  lootGroups:
    common: &id008
      ==: com.crazicrafter1.lootcrates.crate.LootGroup
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: WHITE_STAINED_GLASS_PANE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":"Common
            Reward"}],"text":""}'
      loot:
        - ==: com.crazicrafter1.lootcrates.crate.loot.LootOrdinateItem
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: TNT
          min: 1
          max: 31
        - ==: com.crazicrafter1.lootcrates.crate.loot.LootOrdinateItem
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND
          min: 16
          max: 16
        - ==: com.crazicrafter1.lootcrates.crate.loot.LootOrdinateItem
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: CACTUS
          min: 1
          max: 31
    ultra: &id007
      ==: com.crazicrafter1.lootcrates.crate.LootGroup
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: BLUE_STAINED_GLASS_PANE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":"Ultra
            Reward"}],"text":""}'
      loot:
        - ==: com.crazicrafter1.lootcrates.crate.loot.LootOrdinateItem
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND_BLOCK
          min: 6
          max: 6
        - ==: com.crazicrafter1.lootcrates.crate.loot.LootOrdinateItem
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: OBSIDIAN
          min: 64
          max: 64
        - ==: com.crazicrafter1.lootcrates.crate.loot.LootOrdinateItem
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND_CHESTPLATE
            # test enchantments meta
          min: 1
          max: 1
    legendary: &id009
      ==: com.crazicrafter1.lootcrates.crate.LootGroup
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: RED_STAINED_GLASS_PANE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":"Legendary
            Reward"}],"text":""}'
      loot:
        - ==: com.crazicrafter1.lootcrates.crate.loot.LootOrdinateItem
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND_LEGGINGS
          min: 1
          max: 1
        - ==: com.crazicrafter1.lootcrates.crate.loot.LootOrdinateItem
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND_HELMET
          min: 1
          max: 1
        - ==: com.crazicrafter1.lootcrates.crate.loot.LootOrdinateItem
          item:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: GOLDEN_APPLE
            # test enchantments meta
          min: 8
          max: 8
  crates:
    peasant:
      ==: com.crazicrafter1.lootcrates.crate.Crate
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: CHEST
        meta:
          ==: ItemMeta
          meta-type: TILE_ENTITY
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Peasant
            Loot"}],"text":""}'
          lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Choose
            4 mystery chests, and"}],"text":""}'
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"your
            loot will be revealed!"}],"text":""}'
          internal: H4sIAAAAAAAA/+NiYOBgYHUuSixJZWAvSE0sTswrYQAAGUjyDhUAAAA=
          blockMaterial: CHEST
      header: Peasant crate...
      size: 45
      picks: 3
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      lootGroups:
        *id007: 10
        *id008: 45
    knight:
      ==: com.crazicrafter1.lootcrates.crate.Crate
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: CHEST
        meta:
          ==: ItemMeta
          meta-type: TILE_ENTITY
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Knight
            Loot"}],"text":""}'
          lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Choose
            4 mystery chests, and"}],"text":""}'
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"your
            loot will be revealed!"}],"text":""}'
          internal: H4sIAAAAAAAA/+NiYOBgYHUuSixJZWDLzstMzyhhAAA/nIHiFAAAAA==
          blockMaterial: CHEST
      header: Knight crate...
      size: 45
      picks: 3
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      lootGroups:
        *id009: 15
        *id007: 50
  fireworkEffect:
    ==: Firework
    flicker: false
    trail: false
    colors:
      - ==: Color
        RED: 0
        BLUE: 255
        GREEN: 0
      - ==: Color
        RED: 255
        BLUE: 0
        GREEN: 0
      - ==: Color
        RED: 255
        BLUE: 255
        GREEN: 255
    fade-colors:
      - ==: Color
        RED: 0
        BLUE: 0
        GREEN: 128
    type: BURST
  totalOpens: 0
