data:
  ==: Data
  debug: false
  update: true
  speed: 4
  unSelectedItem:
    ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: CHEST
    meta:
      ==: ItemMeta
      meta-type: TILE_ENTITY
      display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"???"}],"text":""}'
      lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Choose
        4 mystery chests, and"}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"your
        loot will be revealed!"}],"text":""}'
      blockMaterial: CHEST
  selectedItem:
    ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: WHITE_STAINED_GLASS_PANE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"???"}],"text":""}'
      lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"You
        have selected this mystery chest"}],"text":""}'
  lootSets:
    common: &id003
      ==: LootSet
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: WHITE_STAINED_GLASS_PANE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Common
            Reward"}],"text":""}'
          lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Click
            to redeem!"}],"text":""}'
      loot:
        - ==: LootItem
          min: 1
          max: 31
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: TNT
        - ==: LootItem
          min: 32
          max: 32
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: TNT
        - ==: LootItem
          min: 16
          max: 16
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND
        - ==: LootItem
          min: 64
          max: 64
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: CACTUS
        - ==: LootItem
          min: 1
          max: 31
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: COAL
        - ==: LootItem
          min: 1
          max: 31
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: BLAZE_ROD
        - ==: LootItem
          min: 32
          max: 32
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: OBSIDIAN
        - ==: LootItem
          min: 4
          max: 4
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND_BLOCK
        - ==: LootItem
          min: 1
          max: 15
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: POTATO
    regular: &id002
      ==: LootSet
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: YELLOW_STAINED_GLASS_PANE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Regular
            Reward"}],"text":""}'
          lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Click
            to redeem!"}],"text":""}'
      loot:
        - ==: LootItem
          min: 8
          max: 8
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: GOLD_BLOCK
        - ==: LootItem
          min: 1
          max: 31
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: OBSIDIAN
        - ==: LootItemCrate
          min: 1
          max: 1
          crate: peasant
        - ==: LootItem
          min: 16
          max: 16
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND
        - ==: LootItem
          min: 1
          max: 31
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: CACTUS
    ultra: &id001
      ==: LootSet
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: BLUE_STAINED_GLASS_PANE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Ultra
            Reward"}],"text":""}'
          lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Click
            to redeem!"}],"text":""}'
      loot:
        - ==: LootItem
          min: 6
          max: 6
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND_BLOCK
        - ==: LootItem
          min: 64
          max: 64
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: OBSIDIAN
        - ==: LootItem
          min: 1
          max: 1
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND_CHESTPLATE
    rare: &id004
      ==: LootSet
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: PURPLE_STAINED_GLASS_PANE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_purple","text":"Rare
            Reward"}],"text":""}'
          lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Click
            to redeem!"}],"text":""}'
      loot:
        - ==: LootItem
          min: 1
          max: 31
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: TNT
        - ==: LootItem
          min: 16
          max: 16
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND
        - ==: LootItem
          min: 1
          max: 31
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: CACTUS
    legendary: &id005
      ==: LootSet
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: RED_STAINED_GLASS_PANE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Legendary
            Reward"}],"text":""}'
          lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Click
            to redeem!"}],"text":""}'
      loot:
        - ==: LootItem
          min: 1
          max: 1
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND_LEGGINGS
        - ==: LootItem
          min: 1
          max: 1
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: DIAMOND_HELMET
        - ==: LootItem
          min: 8
          max: 8
          itemStack:
            ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: GOLDEN_APPLE
  crates:
    peasant:
      ==: Crate
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: CHEST
        meta:
          ==: ItemMeta
          meta-type: TILE_ENTITY
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white",
            "text":"Peasant Loot"}, {"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray",
            "text":" (Tier 1)"}],"text":""}'
          lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,
            "color":"gray","text":"Right click on this item to unlock"}],"text":""}'
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,
            "color":"gray","text":"four pieces of loot!"}],"text":""}'
          internal: H4sIAAAAAAAA/+NiYOBgYHUuSixJZWAvSE0sTswrYQAAGUjyDhUAAAA=
          blockMaterial: CHEST
      title: 7Choose your Peasant loot
      columns: 3
      picks: 4
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      weights:
        *id001: 8
        *id002: 14
        *id003: 56
    knight:
      ==: Crate
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: CHEST
        meta:
          ==: ItemMeta
          meta-type: TILE_ENTITY
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua",
            "text":"Knight Spoils"}, {"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray",
            "text":" (Tier 2)"}],"text":""}'
          lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,
            "color":"gray","text":"Right click on this item to unlock"}],"text":""}'
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,
            "color":"gray","text":"four pieces of loot!"}],"text":""}'
          internal: H4sIAAAAAAAA/+NiYOBgYHUuSixJZWDLzstMzyhhAAA/nIHiFAAAAA==
          blockMaterial: CHEST
      title: &7Choose your knight spoils
      columns: 3
      picks: 3
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      weights:
        *id002: 7
        *id001: 20
        *id004: 35
        *id005: 42
    king:
      ==: Crate
      itemStack:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: CHEST
        meta:
          ==: ItemMeta
          meta-type: TILE_ENTITY
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red",
            "text":"King Treasure"}, {"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray",
            "text":" (Tier 3)"}],"text":""}'
          lore:
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,
            "color":"gray","text":"Right click on this item to unlock"}],"text":""}'
            - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,
            "color":"gray","text":"four pieces of loot!"}],"text":""}'
          internal: H4sIAAAAAAAA/+NiYOBgYHUuSixJZWDJzsxLZwAApQ9CFhIAAAA=
          blockMaterial: CHEST
      title: &7Choose your king treasure
      columns: 4
      picks: 3
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      weights:
        *id002: 4
        *id001: 20
        *id004: 40
        *id005: 50
  fireworkEffect:
    ==: Firework
    flicker: false
    trail: false
    colors:
      - ==: Color
        RED: 179
        BLUE: 44
        GREEN: 49
      - ==: Color
        RED: 37
        BLUE: 146
        GREEN: 49
      - ==: Color
        RED: 59
        BLUE: 26
        GREEN: 81
    fade-colors:
      - ==: Color
        RED: 59
        BLUE: 26
        GREEN: 81
    type: BURST
