name: LootCrates
main: com.crazicrafter1.lootcrates.Main
version: 3.0.1 # 3.0.0 was previous
api-version: 1.13
author: crazicrafter1
softdepend: [QualityArmory, GraphicalAPI]
commands:
  lootcrates:
    description: Access the features of the loot crates plugin.
    usage: /lootcrates <crate/reload/editor> [type/tier] [player / <*>] [amount]
    permission: lootcrates.admin
    aliases: [crates]
permissions:
  crates.open:
    description: Allow for users to open crates
    default: true
  crates.admin:
    description: Allows access to /crates command
    default: op

# 3.0.1 (3/22/2021)
# crates can *almost* now be edited ingame via a cool looking gui (so close)
# autoupdater

# 3.0.0 (2/19/2021)
# loot types are now completely object oriented
# added custom potion support
# LootGroup chances are cumulatively weighted instead of adding up to 100
# modified format of config, take a gander
# snazzy


# 2.1.7 (11/13/2020)
# fixed update checker


# 2.1.6 (11/13/2020)
# fixed a mis-catched error for config parsing
# and yes works for 1.16.3 and maybe even 1.16.4


# 2.1.5 (8/16/2020)
# fixed some very unexpected bugs that broke mechanics
# 1.16 works!!!


# 2.1.4
# tidied up some loose ends regarding opened crates
# working on gui!
# i think that's it


# 2.1.3
# changed some things to work for 1.8 and maybe earlier


# 2.1.2
# added an * arg to command to target all players