name: LootCrates
main: com.crazicrafter1.lootcrates.Main
version: 3.2.0 # 3.1.4 was previous
api-version: 1.17
depend: [Gapi, CRUtils]
author: crazicrafter1
softdepend: [QualityArmory]
commands:
  lootcrates:
    description: Access the features of the loot crates plugin.
    usage: /lootcrates [crate | detect | editor | flair | reload | version] <id> <player/*> [amount]
    permission: lootcrates.admin
    aliases: [crates, lc]
permissions:
  lootcrates.open:
    description: Allow for users to open crates
    default: true
  lootcrates.admin:
    description: Allows access to /crates command
    default: op

# 3.2.0 (10/3/2021)
# 1.17 only
# in game editor
# config is completely serialized with bukkit, so stay away!
# no more glitches when placing item from guis into inventory


# 3.1.4 (4/26/2021)
# rename permissions


# 3.1.3 (4/6/2021)
# fixed an uncaught error when clicking


# 3.1.2 (4/5/2021)
# 1.8 compatibility


# 3.1.1 (4/5/2021
# added customModelData for texture packs


# 3.1.0 (4/4/2021)
# Highlights:
#   - fixed seasonal crates after being broken for a few months
#   - added config option for seasonal crates
#   - seasonal crates are seasonal (multiple days) instead of on a one day basis
#   - crates are now detected via nbt not name/lore...


# 3.0.2 (4/2/2021)
# fixed mispelled enchantment and added soul speed
# some performance fixes


# 3.0.1 (3/22/2021)
# crates can *almost* now be edited ingame via a cool looking gui (so close)
# autoupdater


# 3.0.0 (2/19/2021)
# loot types are now completely object oriented
# added custom potion support
# LootGroup chances are cumulatively weighted instead of adding up to 100
# modified format of config, take a gander
# snazzy


# 2.1.7 (11/13/2020)
# fixed update checker


# 2.1.6 (11/13/2020)
# fixed a mis-catched error for config parsing
# and yes works for 1.16.3 and maybe even 1.16.4


# 2.1.5 (8/16/2020)
# fixed some very unexpected bugs that broke mechanics
# 1.16 works!!!


# 2.1.4
# tidied up some loose ends regarding opened crates
# working on gui!
# i think that's it


# 2.1.3
# changed some things to work for 1.8 and maybe earlier


# 2.1.2
# added an * arg to command to target all players