name: Lootcrates
version: ${version}
main: com.crazicrafter1.lootcrates.LCMain
api-version: 1.13
depend: [ CRUtils ]
softdepend: [ QualityArmory, Skript, MMOItems ]
authors: [ crazicrafter1 ]
commands:
  lootcrates:
    permission: lootcrates.admin
    aliases: [crates, lc]
  testparser:
    permission: lootcrates.admin
permissions:
  lootcrates.open:
    description: Allow for users to open crates
    default: true
  lootcrates.preview:
    description: Allow crates to be previewed
    default: false
  lootcrates.admin:
    description: Allows access to /crates command
    default: op
libraries:
  - org.apache.commons:commons-lang3:3.12.0